<?
/* 
| Project Sol
| A ~Nolan (http://github.com/mcnolan) production.
|
| Attached Version : 2010/M1
| 
| File : basesetting.php
| 
| Purpose : This file is generated by the install sequence and contains the most basic of settings.
| 
| 
| Sol is copyright Nolan 2010, see README for more details
|
*/
//File auto-generated by the install sequence (well...it will be)
class BaseSetting {

	private static $_adaptor = "Mysql";
	private $_dbHost = "localhost";
	private $_dbUser = "username";
	private $_dbPass = "password";
	private $_dbData = "sol";
	public static $pre = "sol_";
	//This function tells Sol which database class to load
	static function getDatabaseType() {
		return BaseSetting::$_adaptor;
	}
	//This allows the data class to access database details
	protected function getDataSettings() {
		$dbSetting = array("Hostname" => $this->_dbHost, "Username" => $this->_dbUser, "Password" => $this->_dbPass, "Database" => $this->_dbData);
		return $dbSetting;
	}
}
?>
