<?
//File auto-generated by the install sequence (well...it will be)
class BaseSetting {

	private static $_adaptor = "Mysql";
	private $_dbHost = "localhost";
	private $_dbUser = "root";
	private $_dbPass = "ergitz";
	private $_dbData = "sol";
	public static $pre = "sol_";

	static function getDatabaseType() {
		return BaseSetting::$_adaptor;
	}

	protected function getDataSettings() {
		$dbSetting = array("Hostname" => $this->_dbHost, "Username" => $this->_dbUser, "Password" => $this->_dbPass, "Database" => $this->_dbData);
		return $dbSetting;
	}
}
?>
