<table>
<tr>
<td>

<div class="profile_imagebox">
	<img src="http://localhost/Sol/private/nelson.jpg"><br><br>
	<div class="profile_subtext"><img src="http://localhost/Sol/private/r-o5.png"><br>
Commander</div>
</div>


<div class="profile_blurb"><div class="profile_name">Nelson D Grant</div>
<div class="profile_owner">Played by Nolan</div>
<br>
<span class="profile_subheading">Race</span> Human<br>

<span class="profile_subheading">Gender</span> Male<br>

<span class="profile_subheading">Age</span> 32<br>

<div class="profile_heading">Personality</div>
This is the default layout of the character profile page. As you can see, positions the character currently fills are displayed to the right. Any pending applications will appear here when the owning player is logged in.


<div class="profile_heading">Early Life</div>
The user the character is associated with is linked under the character name. In the event this character is public, but the player is not, this link will not show.

<div class="profile_heading">Service History</div>
Each of these Biography headings is stored within the database along with the associated information. This means even if the application forms used by the organisation change, no information is lost from the biography.

<div class="profile_heading">History</div>
Finally, there is a feed of information relating to the character at the bottom of the page, along with any comments made by Users.
</div>




</td>
<td width="25%" class="profile_characters" valign="top">
Current Assignments:<br><br>
	<div class="profile_positions"><img src="http://localhost/Sol/private/bullet_green.png"> Executive Officer
		<div class="hierarchy">Uss Example</div>
	</div>
	<div class="profile_positions"><img src="http://localhost/Sol/private/bullet_red.png"> Personnel Laison
		<div class="hierarchy">Task Force 1</div>
	</div>
</td>

</tr>

<tr>
<td><br>
Character Feed <img src="http://localhost/Sol/private/feed-16px.png">

<div class="profile_comments" width="100%">
	<table width="100%">
		<tr><td rowspan="2" width="40"><img src="http://localhost/Sol/private/feed-grey-32px.png"></td>
		<td class="comment" colspan="2">Lieutenant Commander Nelson D Grant was promoted to Commander!</td></tr>
		<tr><td class="player">Character Feed</td><td class="date">1st April 2010, 11:00am</td></tr>
	</table>
	
	<table width="100%">
		<tr><td rowspan="2" width="40"><img src="http://localhost/Sol/private/feed-grey-32px.png"></td>
		<td class="comment" colspan="2"> Nelson D Grant's profile was updated.</td></tr>
		<tr><td class="player">Character Feed</td><td class="date">21st March 2010, 2:56pm</td></tr>
	</table>

	<table class="indent_one" width="100%">
		<tr><td rowspan="2" width="40"><img src="http://localhost/Sol/private/default.png"></td>
		<td class="comment" colspan="2"><img src="http://localhost/Sol/private/comment.png"> Thought about fleshing out the back story a little more?</td></tr>
		<tr><td class="player">Xavier</td><td class="date">23rd March 2010, 9:08am</td></tr>
	</table>

	<table class="indent_one" width="100%">
		<tr><td rowspan="2" width="40"><img src="http://localhost/Sol/private/nolan_small.jpg"></td>
		<td class="comment" colspan="2"><img src="http://localhost/Sol/private/comment.png"> I'm not too sure what what else I can really put though.</td></tr>
		<tr><td class="player">Nolan</td> <td class="date">23rd March 2010, 9:15am</td></tr>	
	</table>
</div>


</td>
</tr>
</table>
