

<table border="0">
<tr>
<td>

<div class="profile_imagebox"><img src="http://localhost/Sol/private/nolan2.jpg"><br>Member Since : 1st April 2010</div>



<div class="profile_blurb"><h2>Nolan</h2>
This page is the default layout of the User Profile. Common details are to the left, along with the users avatar. Any public characters associated with the player are listed to the right.<br> To the bottom, major events from each characters news feed can optionaly be displayed, along with any custom announcements the player wishes to make. If enabled by the player, other players can make comments on these items.
</div>



</td>
<td class="profile_characters" width="25%">Nolan's Characters<br><br>

<div class="character"><img src="http://localhost/Sol/private/user_green.png" border="0"> <a href="../Character/5">Nolan Demist</a><br><div class="hierarchy">Lieutenant, Uss Testing</div></div>
  
<div class="character"><img src="http://localhost/Sol/private/user_green.png" border="0"> <a href="#">Nelson D Grant</a><br><div class="hierarchy">Commander, Uss Example</div></div>
<div class="character"><img src="http://localhost/Sol/private/user_green.png" border="0"> <a href="#">Fu'a'ri</a><br><div class="hierarchy">Admiral, Task Force 1</div></div>

</td>
</tr>
<tr>
<td>
User Feed <img src="http://localhost/Sol/private/feed-16px.png">


<div class="profile_comments" width="100%">
	<table width="100%">
		<tr><td rowspan="2" width="40"><img src="http://localhost/Sol/private/feed-grey-32px.png"></td>
		<td class="comment" colspan="2">Lieutenant Commander Nelson D Grant was promoted to Commander!</td></tr>
		<tr><td class="player">Character Feed</td><td class="date">1st April 2010, 11:00am</td></tr>
	</table>
	
	<table class="indent_one" width="100%">
		<tr><td rowspan="2" width="40"><img src="http://localhost/Sol/private/default.png"></td>
		<td class="comment" colspan="2"><img src="http://localhost/Sol/private/comment.png"> Grats man, well deserved!</td></tr>
		<tr><td class="player">Player Two</td><td class="date">1st April 2010, 11:05am</td></tr>
	</table>

	<table class="indent_one" width="100%">
		<tr><td rowspan="2" width="40"><img src="http://localhost/Sol/private/nolan_small.jpg" class="floatleft"></td>
		<td class="comment" colspan="2"><img src="http://localhost/Sol/private/comment.png"> Thanks.</td></tr>
		<tr><td class="player">Nolan</td><td class="date">1st April 2010, 11:08am</td></tr>
	</table>

	<table width="100%">
		<tr><td rowspan="2" width="40"><img src="http://localhost/Sol/private/nolan_small.jpg" class="floatleft"></td>
		<td class="comment" colspan="2">Updates to Sol will come on an ad-hoc basis. (In other words, when they're ready)</td></tr>
		<tr><td class="player">Nolan</td> <td class="date">1st April 2010, 9:00am</td></tr>	
	</table>
</div>
</td>
</tr>
</table>
